### ISSUE TITLE
Factorizar 

### ISSUE THREAD

**Issue by pelayoGarcia97** [Arquisoft/Agents_e4a#12]
Hay que mirar para cambiar todas los participants que hay por las clases dentro del htmlController, que hay  por ejemplo:Agent p = (Agent) session.getAttribute("participant");
Son todo cosas así. 

Problemas en las clases:
ChangeInfoHTMLController.java
GetAgentInfoHTMLController.java
RespuestaChangeInfoREST.java
RespuestaInfoREST.java
ChangeInfoRESTController.java
GetAgentInfoRESTController.java

Alomejor hay mas pero bué.

**Comment by CarlosConcheso** [comment]
Todas las nombradas, factorizadas.

RespuestaChangeInfoREST no hacía falta factorizar.
Comprobad y cerrad si no hace falta nada mas por favor 🗡
