### ISSUE TITLE
Wiki InciDashBoard

### ISSUE THREAD

**Issue by pelayoGarcia97** [Arquisoft/Agents_e4a#13]
Tenemos que darle caña a la wiki, he añadido algunas cosas, en stakeholders, comportamiento, atributos de calidad, catalogo de elementos y restricciones técnicas.
Comprobarlo cuando podáis y id añadiendo mas cosas.

**Comment by Pablofernande** [comment]
Añadido en el catálogo de elementos de InciDashboard la información de las relaciones, las propiedades de las interfaces y su tipo. Y la justificación de los atributos de calidad.
