### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Gonzijeje** [Arquisoft/Agents_e4a#3]
-Test con los nuevos atributos
-Test con diferentes tipos de código (Sensor, Entity...)
-Acabar con los tests iniciales

**Comment by Pablofernande** [comment]
Arreglado el test T24testHtmlController de los test iniciales.

**Comment by UO237674** [comment]
T5sensorDoNotExist, T5entityDoNotExist añadidos.
Además de añadir pruebas para sensor y entity en T9emptyPassword

**Comment by Gonzijeje** [comment]
Ahora mismo los test no funcionan debido a la falta de datos en la base de datos. Realizar previamente Issue de Base de Datos(añadir SQLite)
