### ISSUE TITLE
Modelo

### ISSUE THREAD

**Issue by Gonzijeje** [Arquisoft/Agents_e4a#4]
-Quitar campos sobrantes
-Poner los nombres reales
-Decirle a los otros que quiten su atributo que sobra
-Quitar un atributo como público
-Arreglar el atributo "tipo" (String,int) <---

**Comment by Pablofernande** [comment]
Eliminados los campos sobrantes y cambiado el nombre del campo localización.

**Comment by Gonzijeje** [comment]
Eliminada etiqueta Table de la clase Agent, nombres correspondientes con la base de datos.
