### ISSUE TITLE
Comprobación de campos

### ISSUE THREAD

**Issue by Gonzijeje** [Arquisoft/Agents_e4a#7]
-Permitir que la localización pueda ser un campo vacío
-Comptobación de localización actual es String...
-Comprobación de todos los campos en general, para que no solo comprueben que sea un campo vacío o un String (por ej...)

**Comment by Pablofernande** [comment]
Ya esta añadido que la localización pueda ser un campo vacío. Añadidos métodos que comprueban tanto la el correcto formato de la localización así como el del DNI y creado un nuevo tipo de error expecifico para cada uno.
